Style/ConstantNames:
  Excluded:
  - "**/*.cr"

# Performance/AnyInsteadOfEmpty:
#   Excluded:
#   - "**/*.cr"

Lint/UselessAssign:
  Excluded:
  - "**/*.cr"

Lint/NotNil:
  Excluded:
  - "**/*.cr"

Naming/BlockParameterName:
  Excluded:
  - "**/*.cr"